---

- name: fetch/download air-gapped k3s binary for x64
  get_url:
    url: {{ remote_repo_url }}/{{ k3s_version }}/k3s-airgap-images-amd64.tar.gz
    checksum: sha256:{{ remote_repo_url }}/{{ k3s_version }}/sha256sum-amd64.txt
    dest: /var/lib/rancher/k3s/agent/images/k3s-airgap-images-amd64.tar
    owner: root
    group: root
    mode: 0755
  when: ansible_facts.architecture == "x86_64"

- name: fetch/download air-gapped k3s binary for arm64
  get_url:
    url: {{ remote_repo_url }}/{{ k3s_version }}/k3s-airgap-images-arm64.tar.gz
    checksum: sha256:{{ remote_repo_url }}/{{ k3s_version }}/sha256sum-arm64.txt
    dest: /var/lib/rancher/k3s/agent/images/k3s-airgap-images-arm64.tar
    owner: root
    group: root
    mode: 0755
  when:
    - ( ansible_facts.architecture is search("arm") and
        ansible_facts.userspace_bits == "64" ) or
      ansible_facts.architecture is search("aarch64")

- name: fetch/download k3s air-gapped binary for armhf
  get_url:
    url: {{ remote_repo_url }}/{{ k3s_version }}/k3s-airgap-images-arm.tar.gz
    checksum: sha256:{{ remote_repo_url }}/{{ k3s_version }}/sha256sum-arm.txt
    dest: /var/lib/rancher/k3s/agent/images/k3s-airgap-images-arm.tar
    owner: root
    group: root
    mode: 0755
  when:
    - ansible_facts.architecture is search("arm")
    - ansible_facts.userspace_bits == "32"



